# Generated by Django 4.2.21 on 2025-05-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the mass (YYYY-MM-DD)')),
                ('start_time', models.TimeField(help_text='Start time (HH:MM)')),
                ('end_time', models.TimeField(help_text='End time (HH:MM)')),
                ('mass_type', models.CharField(choices=[('morning', 'Morning Mass'), ('evening', 'Evening Mass')], default='morning', help_text='Morning or Evening', max_length=10)),
                ('title_en', models.CharField(help_text='Title in English', max_length=255)),
                ('title_fr', models.CharField(help_text='Titre en Français', max_length=255)),
                ('title_rw', models.CharField(help_text='Title mu Kinyarwanda', max_length=255)),
                ('title_sw', models.CharField(help_text='Title kwa Kiswahili', max_length=255)),
                ('description_en', models.TextField(blank=True, help_text='Description in English')),
                ('description_fr', models.TextField(blank=True, help_text='Description en Français')),
                ('description_rw', models.TextField(blank=True, help_text='Description mu Kinyarwanda')),
                ('description_sw', models.TextField(blank=True, help_text='Description kwa Kiswahili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mass Schedule',
                'verbose_name_plural': 'Mass Schedules',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
