# Generated by Django 4.2.21 on 2025-05-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massschedule',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='massschedule',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='massschedule',
            name='description_rw',
        ),
        migrations.RemoveField(
            model_name='massschedule',
            name='description_sw',
        ),
        migrations.RemoveField(
            model_name='massschedule',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='massschedule',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='massschedule',
            name='title_rw',
        ),
        migrations.RemoveField(
            model_name='massschedule',
            name='title_sw',
        ),
    ]
