# Generated by Django 4.2.21 on 2025-05-27 14:17

import base.models
import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_massschedule_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateField(blank=True, help_text='Date of the homily (YYYY-MM-DD)', null=True)),
                ('title_en', models.CharField(help_text='Title in English', max_length=200)),
                ('title_fr', models.CharField(help_text='Titre en Français', max_length=200)),
                ('title_rw', models.CharField(help_text='Title mu Kinyarwanda', max_length=200)),
                ('title_sw', models.CharField(help_text='Title kwa Kiswahili', max_length=200)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Content in English')),
                ('content_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Contenu en Français')),
                ('content_rw', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Content mu Kinyarwanda')),
                ('content_sw', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Content kwa Kiswahili')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=base.models.homily_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homily',
                'verbose_name_plural': 'Homilies',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
