# Generated by Django 4.2.21 on 2025-05-27 15:27

import base.models
import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_homily'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(help_text='Event date (YYYY-MM-DD)')),
                ('start_time', models.TimeField(blank=True, help_text='Start time (HH:MM)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time (HH:MM)', null=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from English title and date.', max_length=255, unique=True)),
                ('title_en', models.CharField(help_text='Title in English', max_length=200)),
                ('title_fr', models.CharField(help_text='Titre en Français', max_length=200)),
                ('title_rw', models.CharField(help_text='Title mu Kinyarwanda', max_length=200)),
                ('title_sw', models.CharField(help_text='Title kwa Kiswahili', max_length=200)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description in English')),
                ('description_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description en Français')),
                ('description_rw', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description mu Kinyarwanda')),
                ('description_sw', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Description kwa Kiswahili')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Main banner image for the event; auto-cropped and resized.', null=True, upload_to=base.models.event_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date', 'start_time'],
            },
        ),
    ]
