# Generated by Django 4.2.21 on 2025-05-31 14:51

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person giving the testimony', max_length=150)),
                ('email', models.EmailField(help_text='Contact email of the testimony giver', max_length=254)),
                ('testimony_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video')], default='text', help_text='Select whether this is a text, audio, or video testimony', max_length=10)),
                ('content_text', models.TextField(blank=True, help_text='Enter the full text of the testimony (if type is Text).')),
                ('content_file', models.FileField(blank=True, help_text='Upload an audio (mp3/wav) or video (mp4/mov) file. Required if type is Audio or Video.', upload_to=base.models.testimony_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'mp4', 'mov'])])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Set to Published when the testimony is approved to go live.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-created_at'],
            },
        ),
    ]
