# Generated by Django 4.2.21 on 2025-05-31 15:07

import base.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Amenity name (e.g., Free WiFi, Air Conditioning, Breakfast included).', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name/title of the room (e.g., Deluxe Suite, Standard Room).', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title for URL references.', max_length=255, unique=True)),
                ('location', models.CharField(help_text='Physical location or building name (e.g., Main Building, Annex).', max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Detailed description of the room, amenities, and features.')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Nightly rate in USD (decimal allowed, e.g., 149.99).', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, help_text='Select all amenities available for this room.', related_name='rooms', to='base.amenity')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Upload room image; resized to 800×600.', upload_to=base.models.room_image_upload_path)),
                ('alt_text', models.CharField(blank=True, help_text="Alternative text for accessibility (e.g., 'View of Deluxe Suite').", max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
