# Generated by Django 4.2.21 on 2025-05-31 15:27

import base.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_amenity_room_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_en', models.CharField(blank=True, help_text='Caption in English', max_length=200)),
                ('caption_fr', models.CharField(blank=True, help_text='Légende en Français', max_length=200)),
                ('caption_rw', models.CharField(blank=True, help_text='Ishusho mu Kinyarwanda', max_length=200)),
                ('caption_sw', models.CharField(blank=True, help_text='Maelezo kwa Kiswahili', max_length=200)),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Main gallery image resized to 1200×800', upload_to=base.models.gallery_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery',
                'ordering': ['-created_at'],
            },
        ),
    ]
