# Generated by Django 4.2.21 on 2025-05-31 15:47

import base.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the church member', max_length=150)),
                ('role', models.CharField(choices=[('priest', 'Priest'), ('board', 'Board Member')], help_text='Select the member’s role within the church', max_length=20)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Portrait image; will be cropped/downsized to a 400×400 square', null=True, upload_to=base.models.member_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['name'],
            },
        ),
    ]
